// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2/7/2026, 8:07:35 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["C:/www/my-resume/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/www/my-resume/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/www/my-resume/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/www/my-resume/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/www/my-resume/app/plugins/**/*.{js,ts,mjs}","C:/www/my-resume/app/composables/**/*.{js,ts,mjs}","C:/www/my-resume/app/utils/**/*.{js,ts,mjs}","C:/www/my-resume/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/www/my-resume/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/www/my-resume/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/www/my-resume/app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = (() => {const cfg=config;cfg["darkMode"] = ["selector","[class~=\"dark\"]"];;return cfg;})();

export default resolvedConfig;